name: vllm

services:
    vllm-chat:
        container_name: vllm_engine
        image: vllm/vllm-openai:cu130-nightly

        depends_on:
            - prometheus
            - grafana

        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
            - ./config/${CHAT_CONFIG}:/.config/chat.yml

        environment:
            HF_TOKEN: ${HF_TOKEN}

        ports:
            - "8000:8000"
        
        deploy:
            resources:
                reservations:
                    devices:
                          - driver: nvidia
                            count: 1
                            capabilities: [gpu]

        command: >
            --config /.config/chat.yml

    ui-chat:
        container_name: ui_app
        image: ghcr.io/open-webui/open-webui:main-slim

        depends_on:
            - vllm-chat

        volumes:
            - DataOpenWebUI:/app/backend/data

        ports:
            - "8080:8080"

    prometheus:
        container_name: metrics_collector
        image: prom/prometheus:latest

        volumes:
            - ./metrics/prometheus.yml:/prometheus/prometheus.yml
            - DataPrometheus:/prometheus

        ports:
            - "9090:9090"

        command:
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=15d'

    grafana:
        container_name: metrics_dashboard
        image: grafana/grafana:latest

        depends_on:
            - prometheus

        volumes:
            - DataGrafana:/var/lib/grafana

        ports:
            - "3000:3000"

volumes:
    DataOpenWebUI:
    DataPrometheus:
    DataGrafana: