trust-remote-code: True

model: cyankiwi/Qwen3.5-2B-AWQ-4bit
tool-call-parser: qwen3_xml
enable-auto-tool-choice: True 

max-model-len: -1
tokenizer-mode: qwen_vl

gpu-memory-utilization: 0.8
enable-prefix-caching: False
max-num-seqs: 1
block-size: 16

port: 8000 